config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :tasks
  end

  get '/home' => 'home#index'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  belongs_to :user
  validates :category_name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  belongs_to :user
  validates :task_name, presence: true
  validates :task_body, presence: true
  validates :deadline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[edit update destroy]
  
  def index
    @categories = Category.all
    @tasks = Task.all
  end

  def new
  end

  def create
    # @category = Category.new(category_data)
    @category = current_user.categories.build(category_data)
    if @category.save
      redirect_to categories_path, notice: 'Category successfully added.'
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_data)
      redirect_to categories_path, notice: 'Category successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path
    else
      render :index
    end
  end

  def correct_user
    @category = current_user.categories.find_by(id: params[:id])
    redirect_to categories_path, notice: 'Not Authorized to do this action.' if @category.nil?
  end

  private

  def category_data
    params.require(:category).permit(:category_name, :category_body, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category

  def index
    @category_id = params[:category_id]
    @tasks = @category.tasks
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_data)
    if @task.save
      redirect_to category_tasks_path
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_data)
      redirect_to category_tasks_path(@task.category_id)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to category_tasks_path(@task.category_id)
    else
      render :index
    end
  end

  private

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_data
    params.require(:task).permit(:category_id, :task_name, :task_body, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<div>
  <%= form_with scope: :category, url: category_path, method: :put, local: true do |f| %>
    <div>
      <div><%= f.label :category_name, 'Name' %></div>
      <th><%= f.text_field :category_name %></th>
    </div>
    <div>
      <div><%= f.label :category_body, 'Description' %></div>
      <th><%= f.text_field :category_body %></th>
    </div>
    <div>
    <div><%= f.label :deadline, 'Date' %></div>
    <th><%= f.date_field :deadline %></th>
  </div>
    <div>
      <%= f.submit %>
      <button type="button"><%= link_to "Back", categories_path %></button>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
  <div><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></div>
  <div><%= link_to "Edit Profile", edit_user_registration_path %></div>

  <h1>category - index</h1>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<div>
  <button type="button">
  <%= link_to "Add", new_category_path, title: "Add Category" %>
  </button>
</div>

<% @categories.each do |category| %>
  <%if category.user == current_user%>
  <div>
    <div><%= category.category_name %></div>
    <div><%= category.category_body %></div>
  </div>
  <div><%= link_to "Show", category_path(category), title: "Show" %></div>
  <div><%= link_to "Edit", edit_category_path(category.id), title: "Edit" %></div>
  <div><%= link_to "Delete", category_path(category.id), title: "Delete", method: :delete, data: { confirm: 'Are you sure you want to delete this category?' } %></div>      
  <% end %>
<% end %>
<% else %>
  <div><%= link_to "Sign Up", new_user_registration_path %></div>
  <div><%= link_to "Sign In", new_user_session_path %></div>
<% end %>

app/views/categories/new.html.erb
<div>
  <%= form_with scope: :category, url: categories_path, method: :post, local: true do |f| %>
    <div>
      <div><%= f.label :category_name, 'Name' %></div>
      <th><%= f.text_field :category_name %></th>
    </div>
    <div>
      <div><%= f.label :category_body, 'Description' %></div>
      <th><%= f.text_field :category_body %></th>
    </div>
    <div>
      <th><%= f.number_field :user_id, id: :category_user_id, value: current_user.id, type: :hidden %></th>
    </div>
    <div>
      <%= f.submit %>
      <button type="button"><%= link_to "Back", categories_path %></button>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div><%= @category.category_name %></div>
<div><%= @category.category_body %></div>

<button type="button"><%= link_to "Task", category_tasks_path(category_id: @category.id) %></button>
<button type="button"><%= link_to "Back", categories_path %></button>

app/views/home/index.html.erb
<h1>homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div>
  <%= form_with scope: :task, url: category_task_path, method: :put, local: true do |f| %>
    <div>
      <div><%= f.label :task_name, 'Name' %></div>
      <th><%= f.text_field :task_name %></th>
    </div>
    <div>
      <div><%= f.label :task_body, 'Description' %></div>
      <th><%= f.text_field :task_body %></th>
    </div>
    <div>
    <div><%= f.label :deadline, 'Deadline' %></div>
    <th><%= f.date_field :deadline %></th>
  </div>
    <div>
      <%= f.submit %>
      <button type="button"><%= link_to "Back", category_tasks_path %></button>
    </div>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>task - index</h1>

<% @tasks.each do |task| %>
  <div>
    <div><%= task.task_name %></div>
    <div><%= task.task_body %></div>
    <div><%= task.deadline %></div>
  </div>
  <button type="button"><%= link_to "Edit", edit_category_task_path(task.category_id, task.id) %></button>
  <button type="button"><%= link_to "Show", category_task_path(task.category_id, task.id) %></button>
  <button type="button"><%= link_to "Delete", category_task_path(task.category_id, task.id), method: :delete, data: { confirm: 'Are you sure you want to delete this task?' } %></button>
<% end %>

<button type="button"><%= link_to 'Add Task', new_category_task_path(@category_id) %></button>
<button type="button"><%= link_to 'Back', category_path(@category_id) %></button>

app/views/tasks/new.html.erb
<div>
  <%= form_with scope: :task, url: category_tasks_path, method: :post, local: true do |f| %>
    <div>
      <div><%= f.label :task_name, 'Name' %></div>
      <th><%= f.text_field :task_name %></th>
    </div>
    <div>
      <div><%= f.label :task_body, 'Description' %></div>
      <th><%= f.text_field :task_body %></th>
    </div>
    <div>
      <div><%= f.label :deadline, 'Deadline' %></div>
      <th><%= f.date_field :deadline %></th>
    </div>
    <div>
      <%= f.submit %>
      <button type="button"><%= link_to "Back", category_tasks_path %></button>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div><%= @task.task_name %></div>
<div><%= @task.task_body %></div>
<div><%= @task.deadline %></div>

<button type="button"><%= link_to "Back", category_tasks_path(category_id: @category.id) %></button>